# Generated by Django 5.0.6 on 2024-05-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='level',
            field=models.CharField(choices=[('Bgn', 'Beginner'), ('Int', 'Intermediate'), ('Exp', 'Expert')], max_length=3),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
